services:
  vault:
    image: vault:1.9.4
    container_name: vault
    volumes:
    - ./vault-data:/vault/file
    ports:
    - 8200:8200
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_SERVER: http://localhost:8200
      VAULT_ADDR: http://localhost:8200
